# =============================================================================
# app.py — Machine Failure Prediction System
# Phase 2: Streamlit Deployment & Inference Engine
# =============================================================================
# Run with: streamlit run app.py
# Requires: best_model.pkl, scaler.pkl, feature_columns.pkl
#           (generated by train.py)
# =============================================================================

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# =============================================================================
# STEP 1: PAGE CONFIGURATION
# =============================================================================
st.set_page_config(
    page_title="Predictive Maintenance Command Center",
    page_icon="⚙️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# =============================================================================
# STEP 2: LOAD ASSETS (Cached)
# =============================================================================
# @st.cache_resource — caches the loaded objects across all user sessions.
# Without this, Streamlit re-executes the entire script on every interaction,
# which means joblib would reload the model from disk on every slider move.
# cache_resource is designed for heavy, shared objects like ML models.
@st.cache_resource
def load_assets():
    """Load the trained model, scaler, and feature column list from disk."""
    model = joblib.load("best_model.pkl")
    scaler = joblib.load("scaler.pkl")
    feature_columns = joblib.load("feature_columns.pkl")
    return model, scaler, feature_columns

model, scaler, feature_columns = load_assets()

# The numerical columns that were scaled during training —
# we must scale them identically at inference time.
NUMERICAL_COLS = [
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
]

# =============================================================================
# STEP 3: SIDEBAR — SENSOR INPUT PARAMETERS
# =============================================================================
st.sidebar.markdown("## ⚙️ Sensor Inputs")
st.sidebar.markdown("Adjust the live sensor readings from the machine.")
st.sidebar.markdown("---")

# Machine type dropdown
machine_type = st.sidebar.selectbox(
    "Machine Type",
    options=["Low", "Medium", "High"],
    index=0,
    help="Quality variant of the machine (L / M / H)",
)

st.sidebar.markdown("### 🌡️ Temperature")
air_temp = st.sidebar.number_input(
    "Air Temperature [K]",
    min_value=295.0,
    max_value=305.0,
    value=300.0,          # ≈ dataset mean
    step=0.1,
    format="%.1f",
)

process_temp = st.sidebar.number_input(
    "Process Temperature [K]",
    min_value=305.0,
    max_value=315.0,
    value=310.0,          # ≈ dataset mean
    step=0.1,
    format="%.1f",
)

st.sidebar.markdown("### 🔄 Mechanical Load")
rot_speed = st.sidebar.number_input(
    "Rotational Speed [rpm]",
    min_value=1168,
    max_value=2886,
    value=1538,           # ≈ dataset mean
    step=10,
)

torque = st.sidebar.number_input(
    "Torque [Nm]",
    min_value=3.8,
    max_value=76.6,
    value=40.0,           # ≈ dataset mean
    step=0.5,
    format="%.1f",
)

st.sidebar.markdown("### 🔩 Wear")
tool_wear = st.sidebar.number_input(
    "Tool Wear [min]",
    min_value=0,
    max_value=253,
    value=107,            # ≈ dataset mean
    step=1,
)

st.sidebar.markdown("---")
st.sidebar.info("ℹ️ Default values are set to dataset averages for a typical healthy machine.")

# =============================================================================
# STEP 4: MAIN DASHBOARD UI
# =============================================================================
st.title("🏭 Predictive Maintenance Command Center")
st.markdown(
    "Real-time machine failure probability estimation using a trained ML model "
    "on the **AI4I 2020 Predictive Maintenance Dataset**."
)
st.markdown("---")

# Layout: two columns — controls on left, history chart on right
col_left, col_right = st.columns([1, 2])

with col_left:
    st.markdown("### 🎛️ Current Sensor Reading")
    st.markdown(f"- **Machine Type:** `{machine_type}`")
    st.markdown(f"- **Air Temp:** `{air_temp} K`")
    st.markdown(f"- **Process Temp:** `{process_temp} K`")
    st.markdown(f"- **Rotational Speed:** `{rot_speed} rpm`")
    st.markdown(f"- **Torque:** `{torque} Nm`")
    st.markdown(f"- **Tool Wear:** `{tool_wear} min`")
    st.markdown("")
    predict_button = st.button("🔍 Predict Failure", type="primary", use_container_width=True)

with col_right:
    st.markdown("### 📈 Simulated Historical Sensor Trends")
    st.caption("Synthetic rolling-window data for visual context (not real-time).")
    # Generate dummy history chart for visual flair
    # Simulates the last 50 time-steps of 3 key sensor signals
    np.random.seed(42)
    chart_data = pd.DataFrame({
        "Air Temp (K)":       np.random.normal(air_temp,    0.5, 50),
        "Torque (Nm)":        np.random.normal(torque,      2.0, 50),
        "Tool Wear (min)":    np.random.normal(tool_wear,   5.0, 50),
    })
    st.line_chart(chart_data, height=220)

st.markdown("---")

# =============================================================================
# STEP 5: INFERENCE ENGINE (Triggered on Button Click)
# =============================================================================
if predict_button:
    # -------------------------------------------------------------------------
    # 5a. Construct Input Feature Vector
    # -------------------------------------------------------------------------
    # We must build a DataFrame whose columns EXACTLY match the training schema.
    # pandas sorted categories alphabetically → [H, L, M] → drop_first removes H.
    # The model was trained on (Type_L, Type_M). Type_H is the implicit baseline:
    # Type_L=0, Type_M=0 → High machine (the dropped/reference category).

    # pandas sorted categories alphabetically: H, L, M → drop_first drops H.
    # So Type_L=1 means Low, Type_M=1 means Medium; both 0 means High (baseline).
    type_l = 1 if machine_type == "Low" else 0
    type_m = 1 if machine_type == "Medium" else 0

    # Build the raw input dict — unscaled numerical values + one-hot type flags
    raw_input = {
        "Air temperature [K]":      [air_temp],
        "Process temperature [K]":  [process_temp],
        "Rotational speed [rpm]":   [rot_speed],
        "Torque [Nm]":              [torque],
        "Tool wear [min]":          [tool_wear],
        "Type_L":                   [type_l],
        "Type_M":                   [type_m],
    }

    input_df = pd.DataFrame(raw_input)

    # Reorder columns to exactly match the training feature order.
    # Mismatched column orders cause silent wrong predictions — this is a
    # common production bug that feature_columns.pkl guards against.
    input_df = input_df.reindex(columns=feature_columns, fill_value=0)

    # -------------------------------------------------------------------------
    # 5b. Apply Scaling (Selective — Same as Training)
    # -------------------------------------------------------------------------
    # We only scale the numerical columns, NOT the one-hot encoded Type columns,
    # mirroring the selective scaling done in train.py.
    input_df[NUMERICAL_COLS] = scaler.transform(input_df[NUMERICAL_COLS])

    # -------------------------------------------------------------------------
    # 5c. Run Inference
    # -------------------------------------------------------------------------
    # predict_proba returns [[P(class=0), P(class=1)]]
    # We extract index [0][1] → probability of Machine Failure (class 1)
    proba = model.predict_proba(input_df)[0][1]
    failure_pct = proba * 100

    # -------------------------------------------------------------------------
    # 5d. Display Results
    # -------------------------------------------------------------------------
    st.markdown("## 🧠 Prediction Results")
    res_col1, res_col2, res_col3 = st.columns(3)

    with res_col1:
        st.metric(
            label="Failure Probability",
            value=f"{failure_pct:.1f}%",
            delta=f"{'⚠️ High Risk' if failure_pct > 50 else '✅ Low Risk'}",
            delta_color="inverse",
        )

    with res_col2:
        st.metric(
            label="Health Score",
            value=f"{100 - failure_pct:.1f}%",
        )

    with res_col3:
        st.metric(
            label="Confidence Threshold",
            value="50%",
            help="Probability above which a machine is classified as failing.",
        )

    st.markdown("")

    # Prominent status banner
    if failure_pct > 50:
        st.error(
            f"🚨 **CRITICAL ALERT** — Machine failure probability is **{failure_pct:.1f}%**. "
            "Immediate maintenance intervention is recommended. Take the machine offline for inspection."
        )
    else:
        st.success(
            f"✅ **Machine Healthy** — Failure probability is only **{failure_pct:.1f}%**. "
            "All sensor readings are within normal operating parameters. Continue monitoring."
        )

    # Probability gauge as a progress bar
    st.markdown("#### Failure Probability Gauge")
    st.progress(int(failure_pct))

    # Expandable: show the processed feature vector for transparency
    with st.expander("🔬 Technical Detail — Processed Input Vector"):
        st.markdown("*Values after one-hot encoding and standard scaling:*")
        st.dataframe(input_df, use_container_width=True)

else:
    # Placeholder state before the button is pressed
    st.markdown("## 🧠 Prediction Results")
    st.info("👈 Adjust the sensor readings in the sidebar and click **Predict Failure** to run inference.")

# =============================================================================
# FOOTER
# =============================================================================
st.markdown("---")
st.caption(
    "Model trained on the AI4I 2020 Predictive Maintenance Dataset | "
    "Built with Scikit-learn & Streamlit"
)
